Revert "wrlinux-recipelist.conf: Add nodejs support"
Issue: LIN1022-2537

Revert it since world build failed:
ERROR: Nothing RPROVIDES 'nodejs-dev' (but /path/to/layers/meta-openembedded/meta-oe/recipes-devtools/nodejs/nodejs_16.14.2.bb RDEPENDS on or otherwise requires it)

This reverts commit 436984e0deef2ec157c36ed81adec23957193b88.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>