cgl-unittest: use the equivalent standard function
Issue: LINCD-6498

After glibc upgrade to 2.34 [1], some pthread function is
deprecated and removed, so use the equivalent standard
function [2].

Fixed:
 | /build/tmp-glibc/work/corei7-64-wrs-linux/cgl-unittest/1.0-r0/recipe-sysroot-native/usr/bin/x86_64-wrs-linux/../../libexec/x86_64-wrs-linux/gcc/x86_64-wrs-linux/11.2.0/ld: /usr/src/debug/cgl-unittest/1.0-r0/cgl-unittest-1.0/rb-futex/nptl/tst-robust1.c:252: undefined reference to `pthread_mutex_consistent_np'
 | collect2: error: ld returned 1 exit status
 | make[2]: *** [<builtin>: tst-robustpi2] Error 1

[1] https://git.openembedded.org/openembedded-core/commit/?id=af4e1306a78cf8c508dd911f02c103af81bc1af5
[2] https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>