feature/chromium: add wayland & vulkan distro features
Issue: LIN1022-1415

In chromium 104, building without wayland as a DISTRO_FEATURE results
in:
FAILED: obj/third_party/swiftshader/src/Vulkan/swiftshader_libvulkan/VkDescriptorSet.o
| ../../third_party/swiftshader/include/vulkan/vulkan.h:41:10: fatal error: 'wayland-client.h' file not found
| #include <wayland-client.h>

Add both wayland and vulkan to DISTRO_FEATURES since they are
both in our wrlinux-graphics distro definition.

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>