packagegroup-wr-core-net.bb: fix one yocto compatible issue
Issue: LINCD-7249

For wrlinux-distro layer, test_world failed with following error because
during test, nodistro is used:
ERROR: Nothing RPROVIDES '${NETWORK_MANAGER}' (but
/layers/wrlinux/wrlinux-distro/recipes-base/packagegroups/packagegroup-wr-core-net.bb
RDEPENDS on or otherwise requires it)

set NETWORK_MANAGER = ""  to avoid conflict problem between different
network manager, and also fix the yocto compatible issue.

Signed-off-by: Changqing Li <changqing.li@windriver.com>