Revert "wrlinux-distro: remove security layer from LAYERRECOMMENDS"
Issue: LINCD-6217 LINCD-6214 LINCD-6228 LINCD-5809

After below commit introduced in meta-security layer,
c1235f6 meta-security: add sanity check

There comes below warning:
 $ setup.sh --machines intel-x86-64 --distros wrlinux --dl-layers
 $ bitbake wrlinux-image-std
 WARNING: You have included the meta-security layer, but 'security' has not been enabled in your DISTRO_FEATURES. Some bbappend files and preferred version setting may not take effect. See the meta-security README for details on enabling security support.
 [snip]

To silense the above warning, we remove security layer from
LAYERRECOMMENDS to disable security layer by default. But this
change introduces some problems such as:
 $ setup.sh --machine intel-x86-64 --dl-layers --distro wrlinux --templates feature/stig --accept-eula yes
 $ bitbake wrlinux-image-std
 DEBUG: ERROR: Nothing RPROVIDES 'samhain' (but /build/layers/wrlinux/wrlinux-distro/recipes-base/images/wrlinux-image-std.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'samhain' (but /build/layers/wrlinux/wrlinux-distro/recipes-base/images/wrlinux-image-std.bb RDEPENDS on or otherwise requires it)

It's because there is below logic in feature/stig template, but the
recipe samhain which under security layer not enabled by default.
IMAGE_INSTALL += "samhain"

So reverts commit ad7ce9f0b22e9e4976b46f6053c29aeb02eec15a to keep
the original logic as don't want a change which used to silence a
non-fatal warning brings so much issues.

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>