feature/cut: allow cmocka
Issue: LIN1022-872

Fixes:
  ERROR: Required build target 'wrlinux-image-cgl' has no buildable providers.
Missing or unbuildable dependency chain was: ['wrlinux-image-cgl', 'packagegroup-wr-core-cgl', 'frr', 'libyang', 'cmocka']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>